spring:
  application:
    name: Hotel-Admin
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useTimezone=true&serverTimezone=UTC
    username: ${MY_SQL_USERNAME}
    password: ${MY_SQL_PASSWORD}